---
- name: Deploy Docker Image to Container
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Pull Docker Image
      shell: |
        docker pull tendulkaramey/python-calculator-devops

    - name: Create & Start Calculator Docker Container
      docker_container:
        name: python-calculator-devops
        image: tendulkaramey/python-calculator-devops
        state: started
        tty: yes
        interactive: yes