---
- name: Deploy Docker Image to Container
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Get running containers
      docker_host_info:
        containers: yes
      register: docker_info

    - name: Stop running containers
      docker_container:
        name: "{{ item }}"
        state: stopped
      loop: "{{ docker_info.containers | map(attribute='Id') | list }}"
    
    - name: Remove Stoped docker containers
      shell: |
        docker rm $(docker ps -a -q);
      when: (docker_info.containers | length)  != 0

    - name: Get details of all images
      docker_host_info:
        images: yes
        verbose_output: yes
      register: image_info
    
    - name: Remove all images
      docker_image:
        name: "{{ item }}"
        state: absent
      loop: "{{ image_info.images | map(attribute='Id') | list }}"

    - name: Pull Docker Image
      docker_image:
        name: tendulkaramey/python-calculator-devops
        tag: latest
        source: pull

    - name: Create & Start Calculator Docker Container
      docker_container:
        name: python-calculator-devops
        image: tendulkaramey/python-calculator-devops
        state: started
        tty: yes
        interactive: yes